### ISSUE TITLE
Future Maintenance

### ISSUE THREAD

**Issue by agrtga** [LoopeeDK/D35E#5]
@LoopeeDK I read your comment in the Readme. Are you dropping the project completely, or simply lamenting that you don't have enough time to invest in it?

I'm okay with a slower turnaround on support for newer Foundry versions and for bug fixes if the latter. I don't want to see the project die, but I'm in the same situation you are with time. And more than that, although I'm a programmer, the web stack isn't my development focus, so it's not something I can take on. That's not to say I won't take a stab at problems from time-to-time.

**Comment by LoopeeDK** [comment]
well I have more or less dropped it due to time constraint but theres a guy that contacted me on discord that talked about forking the project and taking it over, try writing to Rughalt#4238
